# **Introduction To Numpy**

- It is use for numaricle operation
- is numpy Num Stands for Numerical and py stands for python
- Numpy provides us a structure called as Array which fast compaired to list

In [ ]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8])
print(a)
print(type(a))

[1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>


In [ ]:
d=[6,1,2,3]
g=[]
for i in d:
  g.append(i+2)
print(g)

[8, 3, 4, 5]


In [ ]:
a.ndim

1

In [ ]:
c= np.array([[1,2,3],[4,5,6]])

In [ ]:
c.shape

(2, 3)

In [ ]:
c.size # num of elements present in array

6

In [ ]:
a=np.array([[10,20,30,1],
        [40,50,60,2],
        [70,80,90,3]])

In [ ]:
a[1:,:2]

array([[40, 50],
       [70, 80]])

In [ ]:
a[0:,1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

### **Creating A Special Array**

In [ ]:
# Zero
d=np.zeros(3)
d


array([0., 0., 0.])

In [ ]:
f=np.zeros([2,3])
d

array([0., 0., 0.])

In [ ]:
# Once

w=np.ones(4)
w=np.ones((2,5))
w

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# Full

v=np.full(5,10)
v

array([10, 10, 10, 10, 10])

In [ ]:
# Identity Matrix

In [ ]:
# Create a 3x3 identity matrix
id = np.eye(3)
print(id)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# arange

j=np.arange(1,8)
j
k=np.arange(1,10,3)
k

array([1, 4, 7])

In [ ]:
# Linespace

d=np.linspace(0,10,7)
d

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [ ]:
# Rehshaping

b=np.arange(1,7)
b

array([1, 2, 3, 4, 5, 6])

### **Array Indexing**

In [ ]:
p=np.array([2,4,6,8,10])

In [ ]:
p+2 # Addition
p-2 # Substraction
p*2 # Multiplication
p/2 # Division
p**2 # Power

array([  4,  16,  36,  64, 100])

### **Ststistical Function**

In [ ]:
r=np.array([6,7,8,10,15])
np.min(r)
np.max(r)
np.mean(r)
np.median(r)
np.std(r)
np.var(r)

np.float64(10.16)

In [ ]:
np.sum(r)

np.int64(46)

In [ ]:

np.random.rand(5)

array([0.2491518 , 0.23691883, 0.4206602 , 0.34505538, 0.02136946])

In [ ]:
np.random.randint(1,10,8)

array([1, 6, 9, 2, 6, 5, 3, 6])